-- =====================================================================
-- V1 — Schema initial KFOKAM48
-- Normatif : ces 7 tables sont exactement celles annoncees par
-- docs/diagrammes/D2.md. SQL volontairement portable (PostgreSQL 16 en
-- developpement, H2 en mode PostgreSQL pour les tests).
-- Aucune evolution de ce fichier : toute modification passe par V3, V4...
-- =====================================================================

-- ---------------------------------------------------------------------
-- promotions : le formateur anime une promotion (Q16, promotionId du contrat)
-- ---------------------------------------------------------------------
CREATE TABLE promotions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nom        VARCHAR(120) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT pk_promotions PRIMARY KEY (id),
    CONSTRAINT uq_promotions_nom UNIQUE (nom)
);

-- ---------------------------------------------------------------------
-- etudiants : le nom sert de selection dans la liste (Q1, aucune authentification)
-- ---------------------------------------------------------------------
CREATE TABLE etudiants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    promotion_id BIGINT       NOT NULL,
    nom          VARCHAR(80)  NOT NULL,
    prenom       VARCHAR(80)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_etudiants PRIMARY KEY (id),
    CONSTRAINT fk_etudiants_promotion FOREIGN KEY (promotion_id) REFERENCES promotions (id)
);

CREATE INDEX ix_etudiants_promotion ON etudiants (promotion_id);

-- ---------------------------------------------------------------------
-- sessions : deux jalons distincts (decision 7.5 du cahier des charges)
--   expiration_at = fin des presences (Q2, Q3)
--   cloture_at    = fin des depots et des presences, action du formateur (Q12)
-- ---------------------------------------------------------------------
CREATE TABLE sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    promotion_id  BIGINT       NOT NULL,
    titre         VARCHAR(160) NOT NULL,
    code          VARCHAR(6)   NOT NULL,
    ouverture_at  TIMESTAMP    NOT NULL,
    expiration_at TIMESTAMP    NOT NULL,
    cloture_at    TIMESTAMP,
    CONSTRAINT pk_sessions PRIMARY KEY (id),
    CONSTRAINT uq_sessions_code UNIQUE (code),
    CONSTRAINT fk_sessions_promotion FOREIGN KEY (promotion_id) REFERENCES promotions (id)
);

CREATE INDEX ix_sessions_promotion ON sessions (promotion_id);

-- ---------------------------------------------------------------------
-- presences : unicite portee par la base (RG4), origine de la saisie (Q14, RG17)
-- ---------------------------------------------------------------------
CREATE TABLE presences (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id  BIGINT      NOT NULL,
    etudiant_id BIGINT      NOT NULL,
    source      VARCHAR(10) NOT NULL,
    ajoutee_at  TIMESTAMP   NOT NULL,
    CONSTRAINT pk_presences PRIMARY KEY (id),
    CONSTRAINT uq_presences_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presences_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT fk_presences_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_presences_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiants (id)
);

-- ---------------------------------------------------------------------
-- exercices : un depot par etudiant et par session, cycle de vie porte par
-- statut (D4). DEPOSE n'existe que le temps de la transaction de depot.
-- ---------------------------------------------------------------------
CREATE TABLE exercices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id  BIGINT       NOT NULL,
    etudiant_id BIGINT       NOT NULL,
    lien        VARCHAR(500) NOT NULL,
    statut      VARCHAR(20)  NOT NULL,
    depose_at   TIMESTAMP    NOT NULL,
    maj_at      TIMESTAMP    NOT NULL,
    CONSTRAINT pk_exercices PRIMARY KEY (id),
    CONSTRAINT uq_exercices_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercices_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE', 'SANS_RELECTEUR', 'RELU')),
    CONSTRAINT fk_exercices_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_exercices_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiants (id)
);

CREATE INDEX ix_exercices_session ON exercices (session_id);

-- ---------------------------------------------------------------------
-- relectures : un seul relecteur par exercice (Q6, RG7). Une note non nulle
-- implique un rendu (RG12) : note, commentaire et rendu_at restent nullables
-- tant que la relecture n'est pas rendue. Aucune colonne ne permet de
-- reecrire une note : c'est volontaire (Q15, decision 7.1).
-- ---------------------------------------------------------------------
CREATE TABLE relectures (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exercice_id      BIGINT      NOT NULL,
    relecteur_id     BIGINT      NOT NULL,
    statut           VARCHAR(20) NOT NULL,
    assigne_par      VARCHAR(10) NOT NULL,
    assigne_at       TIMESTAMP   NOT NULL,
    lien_consulte_at TIMESTAMP,
    note             INTEGER,
    commentaire      VARCHAR(2000),
    rendu_at         TIMESTAMP,
    CONSTRAINT pk_relectures PRIMARY KEY (id),
    CONSTRAINT uq_relectures_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relectures_statut CHECK (statut IN ('EN_ATTENTE', 'RENDUE')),
    CONSTRAINT ck_relectures_assigne_par CHECK (assigne_par IN ('SYSTEME', 'FORMATEUR')),
    CONSTRAINT ck_relectures_note CHECK (note IS NULL OR (note >= 0 AND note <= 20)),
    CONSTRAINT fk_relectures_exercice FOREIGN KEY (exercice_id) REFERENCES exercices (id),
    CONSTRAINT fk_relectures_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiants (id)
);

-- ---------------------------------------------------------------------
-- tentatives_code : compteur d'echecs par etudiant (Q4, RG5, H7)
-- ---------------------------------------------------------------------
CREATE TABLE tentatives_code (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    etudiant_id    BIGINT    NOT NULL,
    nb_echecs      INTEGER   NOT NULL DEFAULT 0,
    bloque_jusqu_a TIMESTAMP,
    maj_at         TIMESTAMP NOT NULL,
    CONSTRAINT pk_tentatives_code PRIMARY KEY (id),
    CONSTRAINT uq_tentatives_code_etudiant UNIQUE (etudiant_id),
    CONSTRAINT fk_tentatives_code_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiants (id)
);
