-- =====================================================================
-- V3 — Audit des assignations manuelles (RG23, enveloppe étape 3)
-- Changement de besoin (issue 16) : le formateur désigne un relecteur aux
-- exercices restés SANS_RELECTEUR directement depuis l'écran du tableau.
-- La voie de secours devient d'un usage courant : elle laisse une trace
-- (qui, pour quel exercice, quel relecteur, quand), exigence RG23.
-- Cette table d'observation ne change aucun comportement métier.
-- V1 et V2 restent inchangées : toute évolution passe par une nouvelle
-- migration, jamais par la retouche d'un fichier déjà commité.
-- =====================================================================

CREATE TABLE audits_assignation_manuelle (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exercice_id    BIGINT    NOT NULL,
    relecteur_id   BIGINT    NOT NULL,
    assigne_par_id BIGINT    NOT NULL,
    assigne_at     TIMESTAMP NOT NULL,
    CONSTRAINT pk_audits_assignation_manuelle PRIMARY KEY (id),
    CONSTRAINT fk_audit_exercice FOREIGN KEY (exercice_id) REFERENCES exercices (id),
    CONSTRAINT fk_audit_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiants (id),
    CONSTRAINT fk_audit_assigne_par FOREIGN KEY (assigne_par_id) REFERENCES etudiants (id)
);

CREATE INDEX ix_audits_assignation_exercice ON audits_assignation_manuelle (exercice_id);

ALTER TABLE audits_assignation_manuelle ALTER COLUMN id RESTART WITH 1000;
